In [3]:
c_alpha = [2, 11, 20, 27, 32, 37, 42, 51, 62, 71, 82, 91, 101, 109, 117]

for i in range(len(c_alpha)-1):
    print(f'd{i}: DISTANCE ATOMS={c_alpha[i]},{c_alpha[i+1]}')

d0: DISTANCE ATOMS=2,11
d1: DISTANCE ATOMS=11,20
d2: DISTANCE ATOMS=20,27
d3: DISTANCE ATOMS=27,32
d4: DISTANCE ATOMS=32,37
d5: DISTANCE ATOMS=37,42
d6: DISTANCE ATOMS=42,51
d7: DISTANCE ATOMS=51,62
d8: DISTANCE ATOMS=62,71
d9: DISTANCE ATOMS=71,82
d10: DISTANCE ATOMS=82,91
d11: DISTANCE ATOMS=91,101
d12: DISTANCE ATOMS=101,109
d13: DISTANCE ATOMS=109,117

In [9]:
c_alpha = [2, 11, 20, 27, 32, 37, 42, 51, 62, 71, 82, 91, 101, 109, 117]

counter = 1
for i in range(len(c_alpha)):
    for j in range(i+1, len(c_alpha)):  
        print(f'd{counter}: DISTANCE ATOMS = {c_alpha[i]},{c_alpha[j]}')
        counter+=1

d1: DISTANCE ATOMS = 2,11
d2: DISTANCE ATOMS = 2,20
d3: DISTANCE ATOMS = 2,27
d4: DISTANCE ATOMS = 2,32
d5: DISTANCE ATOMS = 2,37
d6: DISTANCE ATOMS = 2,42
d7: DISTANCE ATOMS = 2,51
d8: DISTANCE ATOMS = 2,62
d9: DISTANCE ATOMS = 2,71
d10: DISTANCE ATOMS = 2,82
d11: DISTANCE ATOMS = 2,91
d12: DISTANCE ATOMS = 2,101
d13: DISTANCE ATOMS = 2,109
d14: DISTANCE ATOMS = 2,117
d15: DISTANCE ATOMS = 11,20
d16: DISTANCE ATOMS = 11,27
d17: DISTANCE ATOMS = 11,32
d18: DISTANCE ATOMS = 11,37
d19: DISTANCE ATOMS = 11,42
d20: DISTANCE ATOMS = 11,51
d21: DISTANCE ATOMS = 11,62
d22: DISTANCE ATOMS = 11,71
d23: DISTANCE ATOMS = 11,82
d24: DISTANCE ATOMS = 11,91
d25: DISTANCE ATOMS = 11,101
d26: DISTANCE ATOMS = 11,109
d27: DISTANCE ATOMS = 11,117
d28: DISTANCE ATOMS = 20,27
d29: DISTANCE ATOMS = 20,32
d30: DISTANCE ATOMS = 20,37
d31: DISTANCE ATOMS = 20,42
d32: DISTANCE ATOMS = 20,51
d33: DISTANCE ATOMS = 20,62
d34: DISTANCE ATOMS = 20,71
d35: DISTANCE ATOMS = 20,82
d36: DISTANCE ATOMS = 20,91
d37: DISTANCE ATOMS = 20,101
d38: DISTANCE ATOMS = 20,109
d39: DISTANCE ATOMS = 20,117
d40: DISTANCE ATOMS = 27,32
d41: DISTANCE ATOMS = 27,37
d42: DISTANCE ATOMS = 27,42
d43: DISTANCE ATOMS = 27,51
d44: DISTANCE ATOMS = 27,62
d45: DISTANCE ATOMS = 27,71
d46: DISTANCE ATOMS = 27,82
d47: DISTANCE ATOMS = 27,91
d48: DISTANCE ATOMS = 27,101
d49: DISTANCE ATOMS = 27,109
d50: DISTANCE ATOMS = 27,117
d51: DISTANCE ATOMS = 32,37
d52: DISTANCE ATOMS = 32,42
d53: DISTANCE ATOMS = 32,51
d54: DISTANCE ATOMS = 32,62
d55: DISTANCE ATOMS = 32,71
d56: DISTANCE ATOMS = 32,82
d57: DISTANCE ATOMS = 32,91
d58: DISTANCE ATOMS = 32,101
d59: DISTANCE ATOMS = 32,109
d60: DISTANCE ATOMS = 32,117
d61: DISTANCE ATOMS = 37,42
d62: DISTANCE ATOMS = 37,51
d63: DISTANCE ATOMS = 37,62
d64: DISTANCE ATOMS = 37,71
d65: DISTANCE ATOMS = 37,82
d66: DISTANCE ATOMS = 37,91
d67: DISTANCE ATOMS = 37,101
d68: DISTANCE ATOMS = 37,109
d69: DISTANCE ATOMS = 37,117
d70: DISTANCE ATOMS = 42,51
d71: DISTANCE ATOMS = 42,62
d72: DISTANCE ATOMS = 42,71
d73: DISTANCE ATOMS = 42,82
d74: DISTANCE ATOMS = 42,91
d75: DISTANCE ATOMS = 42,101
d76: DISTANCE ATOMS = 42,109
d77: DISTANCE ATOMS = 42,117
d78: DISTANCE ATOMS = 51,62
d79: DISTANCE ATOMS = 51,71
d80: DISTANCE ATOMS = 51,82
d81: DISTANCE ATOMS = 51,91
d82: DISTANCE ATOMS = 51,101
d83: DISTANCE ATOMS = 51,109
d84: DISTANCE ATOMS = 51,117
d85: DISTANCE ATOMS = 62,71
d86: DISTANCE ATOMS = 62,82
d87: DISTANCE ATOMS = 62,91
d88: DISTANCE ATOMS = 62,101
d89: DISTANCE ATOMS = 62,109
d90: DISTANCE ATOMS = 62,117
d91: DISTANCE ATOMS = 71,82
d92: DISTANCE ATOMS = 71,91
d93: DISTANCE ATOMS = 71,101
d94: DISTANCE ATOMS = 71,109
d95: DISTANCE ATOMS = 71,117
d96: DISTANCE ATOMS = 82,91
d97: DISTANCE ATOMS = 82,101
d98: DISTANCE ATOMS = 82,109
d99: DISTANCE ATOMS = 82,117
d100: DISTANCE ATOMS = 91,101
d101: DISTANCE ATOMS = 91,109
d102: DISTANCE ATOMS = 91,117
d103: DISTANCE ATOMS = 101,109
d104: DISTANCE ATOMS = 101,117
d105: DISTANCE ATOMS = 109,117

In [57]:
print('#-----INPUT ------')
print('')
print('MOLINFO MOLTYPE=protein STRUCTURE=input.pdb')
print('')
no_resid = 15  

print('')
print('#-----TORSION ------')
print('')

for i in range(no_resid):
    if (i > 1 or i == 1) and i != 14:  
        print(f'phi{i+1}: TORSION ATOMS=@phi-{i+1}')
        print(f'psi{i+1}: TORSION ATOMS=@psi-{i+1}')

print('')
print('#-----COS TORSION ------')
print('')

for j in range(no_resid):
     if (j > 1 or j == 1) and j != 14: 
        print(f'cos_ph{j+1}: MATHEVAL ARG=phi{j+1} FUNC=0.5+cos(x-1.25) PERIODIC=NO')
        print(f'cos_ps{j+1}: MATHEVAL ARG=psi{j+1} FUNC=0.5+cos(x-1.25) PERIODIC=NO')
        

print('')        
print('PRINT ARG=* STRIDE=2 FILE=COLVAR_tor_f FMT=%8.4f')

#-----INPUT ------

MOLINFO MOLTYPE=protein STRUCTURE=input.pdb


#-----TORSION ------

phi2: TORSION ATOMS=@phi-2
psi2: TORSION ATOMS=@psi-2
phi3: TORSION ATOMS=@phi-3
psi3: TORSION ATOMS=@psi-3
phi4: TORSION ATOMS=@phi-4
psi4: TORSION ATOMS=@psi-4
phi5: TORSION ATOMS=@phi-5
psi5: TORSION ATOMS=@psi-5
phi6: TORSION ATOMS=@phi-6
psi6: TORSION ATOMS=@psi-6
phi7: TORSION ATOMS=@phi-7
psi7: TORSION ATOMS=@psi-7
phi8: TORSION ATOMS=@phi-8
psi8: TORSION ATOMS=@psi-8
phi9: TORSION ATOMS=@phi-9
psi9: TORSION ATOMS=@psi-9
phi10: TORSION ATOMS=@phi-10
psi10: TORSION ATOMS=@psi-10
phi11: TORSION ATOMS=@phi-11
psi11: TORSION ATOMS=@psi-11
phi12: TORSION ATOMS=@phi-12
psi12: TORSION ATOMS=@psi-12
phi13: TORSION ATOMS=@phi-13
psi13: TORSION ATOMS=@psi-13
phi14: TORSION ATOMS=@phi-14
psi14: TORSION ATOMS=@psi-14

#-----COS TORSION ------

cos_ph2: MATHEVAL ARG=phi2 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps2: MATHEVAL ARG=psi2 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph3: MATHEVAL ARG=phi3 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps3: MATHEVAL ARG=psi3 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph4: MATHEVAL ARG=phi4 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps4: MATHEVAL ARG=psi4 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph5: MATHEVAL ARG=phi5 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps5: MATHEVAL ARG=psi5 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph6: MATHEVAL ARG=phi6 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps6: MATHEVAL ARG=psi6 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph7: MATHEVAL ARG=phi7 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps7: MATHEVAL ARG=psi7 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph8: MATHEVAL ARG=phi8 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps8: MATHEVAL ARG=psi8 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph9: MATHEVAL ARG=phi9 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps9: MATHEVAL ARG=psi9 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph10: MATHEVAL ARG=phi10 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps10: MATHEVAL ARG=psi10 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph11: MATHEVAL ARG=phi11 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps11: MATHEVAL ARG=psi11 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph12: MATHEVAL ARG=phi12 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps12: MATHEVAL ARG=psi12 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph13: MATHEVAL ARG=phi13 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps13: MATHEVAL ARG=psi13 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ph14: MATHEVAL ARG=phi14 FUNC=0.5+cos(x-1.25) PERIODIC=NO
cos_ps14: MATHEVAL ARG=psi14 FUNC=0.5+cos(x-1.25) PERIODIC=NO

PRINT ARG=* STRIDE=2 FILE=COLVAR_tor_f FMT=%8.4f

In [1]:
""""import numpy as np

#for i in range(106):
#    print(f'{i+1}',end=',')

f = np.loadtxt('md_sim/folded/COLVAR_f')
m = np.loadtxt('md_sim/misfolded/COLVAR_m')
u = np.loadtxt('md_sim/unfolded/COLVAR_u')

header="time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45,d46,d47,d48,d49,d50,d51,d52,d53,d54,d55,d56,d57,d58,d59,d60,d61,d62,d63,d64,d65,d66,d67,d68,d69,d70,d71,d72,d73,d74,d75,d76,d77,d78,d79,d80,d81,d82,d83,d84,d85,d86,d87,d88,d89,d90,d91,d92,d93,d94,d95,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105"

np.savetxt("COLVAR_f.csv", f, delimiter=",", header=header, comments="")
np.savetxt("COLVAR_m.csv", m, delimiter=",", header=header, comments="")
np.savetxt("COLVAR_u.csv", u, delimiter=",", header=header, comments="")"""

In [7]:
"""import pandas as pd

df_f = pd.read_csv('COLVAR_f.csv')
df_f"""

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105
0,0.000000,0.0470,0.7760,0.4100,0.3948,2.0190,0.4760,0.6962,0.5352,0.7041,...,0.4961,0.9223,0.5174,0.7716,0.4435,0.4891,0.7113,0.6860,0.7786,0.2968
1,0.100000,0.0420,0.7769,0.4319,0.3956,2.0451,0.4784,0.7403,0.5174,0.6990,...,0.5026,0.9494,0.5347,0.7864,0.4640,0.4917,0.7133,0.6966,0.7802,0.3074
2,0.200000,0.0402,0.7813,0.4468,0.3973,2.0262,0.4617,0.7167,0.5184,0.7306,...,0.5022,0.9459,0.5411,0.7793,0.4533,0.4987,0.6999,0.7204,0.8016,0.3001
3,0.300000,0.0400,0.7808,0.4277,0.3847,2.0144,0.4652,0.7172,0.5118,0.7174,...,0.5031,0.9467,0.5325,0.7788,0.4487,0.4796,0.6801,0.7284,0.7969,0.3301
4,0.400000,0.0518,0.7762,0.4176,0.3959,2.0050,0.4655,0.7313,0.5074,0.7070,...,0.5075,0.9557,0.5348,0.7720,0.4618,0.5278,0.7364,0.7693,0.8481,0.3457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999.600047,0.1790,0.8018,0.7083,0.3827,2.0380,0.4235,0.7455,0.5204,0.7212,...,0.5046,0.8706,0.5204,0.6328,0.4084,0.4633,0.3989,0.7916,0.6187,0.2346
9997,999.700047,0.1809,0.8039,0.7121,0.3856,2.0282,0.3975,0.7131,0.4987,0.6944,...,0.5086,0.8944,0.5332,0.6342,0.4168,0.5105,0.4418,0.8217,0.6487,0.2299
9998,999.800047,0.1787,0.8082,0.7085,0.4020,2.0369,0.4168,0.7399,0.4996,0.6571,...,0.5230,0.8973,0.5389,0.6826,0.4176,0.4760,0.4898,0.8030,0.7030,0.2235
9999,999.900047,0.1768,0.8136,0.7109,0.4077,2.0867,0.4356,0.7722,0.4721,0.6336,...,0.5006,0.8817,0.5299,0.6826,0.4231,0.4824,0.5183,0.7744,0.6888,0.2103
10000,1000.000047,0.1719,0.8093,0.7245,0.3882,2.0887,0.3946,0.7177,0.5139,0.7194,...,0.5044,0.9028,0.5481,0.6835,0.4193,0.4852,0.4823,0.7817,0.6598,0.2208

In [6]:
"""df_m = pd.read_csv('COLVAR_m.csv')
df_m"""

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105
0,0.000000,0.3163,0.9291,1.2939,1.3629,1.3847,0.4494,0.7336,0.5356,0.8012,...,0.4359,0.8671,0.5315,0.5033,0.4597,0.4865,0.5697,0.8346,0.8266,0.4923
1,0.100000,0.3116,0.9279,1.2780,1.3660,1.3697,0.4612,0.7712,0.5362,0.8045,...,0.4442,0.8639,0.5169,0.5259,0.4539,0.4689,0.5819,0.8313,0.8347,0.4757
2,0.200000,0.3049,0.9226,1.2753,1.3554,1.3673,0.4623,0.7520,0.5408,0.8025,...,0.4397,0.8840,0.5207,0.5375,0.4702,0.4586,0.5274,0.8284,0.7796,0.4747
3,0.300000,0.3001,0.9231,1.2647,1.4089,1.3637,0.4291,0.7776,0.5059,0.7670,...,0.4520,0.8938,0.5398,0.5146,0.4662,0.4697,0.4769,0.8323,0.7353,0.4699
4,0.400000,0.2919,0.9191,1.2697,1.4145,1.3574,0.4548,0.7715,0.5309,0.7903,...,0.4513,0.8707,0.5259,0.5509,0.4565,0.4595,0.4981,0.8223,0.7065,0.4630
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999.600047,0.3362,0.9080,1.3078,1.8860,2.1028,0.3797,0.6629,0.5072,0.7654,...,0.4370,0.8614,0.5338,0.6567,0.4569,0.4687,0.5382,0.8191,0.6782,0.4857
9997,999.700047,0.3346,0.9063,1.2885,1.8738,2.0694,0.3433,0.6770,0.5220,0.7734,...,0.4310,0.8441,0.5237,0.5795,0.4481,0.4830,0.5188,0.8030,0.6552,0.4773
9998,999.800047,0.3346,0.9104,1.2810,1.9256,2.1200,0.3737,0.6981,0.5416,0.7955,...,0.4313,0.8355,0.5334,0.5454,0.4432,0.4798,0.4782,0.8213,0.6521,0.4734
9999,999.900047,0.3360,0.9107,1.2989,1.9637,2.0964,0.4042,0.7035,0.5302,0.7878,...,0.4266,0.8606,0.5299,0.5625,0.4595,0.4902,0.4842,0.8516,0.7044,0.4537
10000,1000.000047,0.3348,0.9114,1.3048,1.9828,2.0890,0.3975,0.6825,0.5205,0.7811,...,0.4425,0.8532,0.5329,0.5847,0.4360,0.5142,0.5339,0.8485,0.7155,0.4940

In [8]:
"""df_u = pd.read_csv('COLVAR_u.csv')
df_u"""

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105
0,0.000000,0.5792,0.6716,1.0476,1.1995,0.2575,0.4962,0.8465,0.4495,0.6669,...,0.4415,0.8663,0.5260,0.4370,0.4285,0.4802,0.3897,0.7906,0.7239,0.3995
1,0.100000,0.5856,0.6733,1.0563,1.1869,0.2738,0.4995,0.8439,0.4649,0.6867,...,0.4457,0.8549,0.5176,0.4422,0.4185,0.4638,0.4091,0.7885,0.7152,0.4192
2,0.200000,0.5870,0.6737,1.0681,1.1972,0.2589,0.4977,0.8359,0.4486,0.6692,...,0.4344,0.8465,0.5208,0.4153,0.4132,0.4832,0.3813,0.7614,0.7010,0.4232
3,0.300000,0.5837,0.6755,1.0744,1.1986,0.2408,0.5029,0.8519,0.4658,0.6916,...,0.4487,0.8509,0.5321,0.4693,0.4036,0.4939,0.3933,0.7534,0.6860,0.4077
4,0.400000,0.5766,0.6738,1.0911,1.2014,0.2742,0.4900,0.8266,0.4630,0.6870,...,0.4512,0.8598,0.5270,0.5286,0.4102,0.4753,0.4181,0.7443,0.6877,0.4364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9996,999.600047,0.4643,0.7371,1.1154,0.9866,1.4998,0.4693,0.8184,0.4465,0.6782,...,0.4199,0.8270,0.5163,0.3769,0.4169,0.4449,0.4429,0.7506,0.7650,0.4113
9997,999.700047,0.4620,0.7390,1.1050,0.9475,1.5026,0.4841,0.8569,0.4681,0.6965,...,0.4292,0.8373,0.5361,0.3795,0.4156,0.4800,0.4327,0.7845,0.7659,0.4198
9998,999.800047,0.4607,0.7394,1.0976,0.9314,1.4839,0.4711,0.8165,0.4602,0.6825,...,0.4368,0.8299,0.5292,0.3602,0.4097,0.4856,0.4392,0.7996,0.7485,0.4264
9999,999.900047,0.4604,0.7393,1.0949,0.9301,1.4739,0.4810,0.8699,0.4521,0.6781,...,0.4205,0.8247,0.5246,0.3995,0.4093,0.4952,0.4201,0.7949,0.7375,0.4130
10000,1000.000047,0.4657,0.7401,1.0842,0.9305,1.4701,0.4888,0.8607,0.4713,0.7048,...,0.4231,0.8237,0.5417,0.3953,0.4026,0.5182,0.4206,0.7917,0.7320,0.4205

## file.csv prep

In [1]:
import numpy as np

f = np.loadtxt('COLVAR_f')
state_column = np.zeros((f.shape[0], 1))

f_with_state = np.column_stack((f, state_column))

header = "time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45,d46,d47,d48,d49,d50,d51,d52,d53,d54,d55,d56,d57,d58,d59,d60,d61,d62,d63,d64,d65,d66,d67,d68,d69,d70,d71,d72,d73,d74,d75,d76,d77,d78,d79,d80,d81,d82,d83,d84,d85,d86,d87,d88,d89,d90,d91,d92,d93,d94,d95,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105,State"
np.savetxt("COLVAR_f.csv", f_with_state, delimiter=",", header=header, comments="")

In [7]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 2.9 MB/s eta 0:00:00m eta 0:00:01[36m0:00:01
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 KB 6.1 MB/s eta 0:00:00[36m0:00:01
Requirement already satisfied: numpy>=1.22.4 in /home/revanth/.local/lib/python3.10/site-packages (from pandas) (2.1.3)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas) (2022.1)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.8/346.8 KB 9.3 MB/s eta 0:00:00[36m0:00:01
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, python-dateutil, pandas
Successfully installed pandas-2.2.3 python-dateutil-2.9.0.post0 tzdata-2025.1

In [2]:
import pandas as pd

df_f = pd.read_csv('COLVAR_f.csv')
df_f.head(5)

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d97,d98,d99,d100,d101,d102,d103,d104,d105,State
0,0.0,0.0470,0.7760,0.4100,0.3948,2.0190,0.4760,0.6962,0.5352,0.7041,...,0.9223,0.5174,0.7716,0.4435,0.4891,0.7113,0.6860,0.7786,0.2968,0.0
1,0.1,0.0420,0.7769,0.4319,0.3956,2.0451,0.4784,0.7403,0.5174,0.6990,...,0.9494,0.5347,0.7864,0.4640,0.4917,0.7133,0.6966,0.7802,0.3074,0.0
2,0.2,0.0402,0.7813,0.4468,0.3973,2.0262,0.4617,0.7167,0.5184,0.7306,...,0.9459,0.5411,0.7793,0.4533,0.4987,0.6999,0.7204,0.8016,0.3001,0.0
3,0.3,0.0400,0.7808,0.4277,0.3847,2.0144,0.4652,0.7172,0.5118,0.7174,...,0.9467,0.5325,0.7788,0.4487,0.4796,0.6801,0.7284,0.7969,0.3301,0.0
4,0.4,0.0518,0.7762,0.4176,0.3959,2.0050,0.4655,0.7313,0.5074,0.7070,...,0.9557,0.5348,0.7720,0.4618,0.5278,0.7364,0.7693,0.8481,0.3457,0.0

In [3]:
#import numpy as np

m = np.loadtxt('COLVAR_m')
state_column = np.ones((m.shape[0], 1))

m_with_state = np.column_stack((m, state_column))

header = "time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45,d46,d47,d48,d49,d50,d51,d52,d53,d54,d55,d56,d57,d58,d59,d60,d61,d62,d63,d64,d65,d66,d67,d68,d69,d70,d71,d72,d73,d74,d75,d76,d77,d78,d79,d80,d81,d82,d83,d84,d85,d86,d87,d88,d89,d90,d91,d92,d93,d94,d95,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105,State"
np.savetxt("COLVAR_m.csv", m_with_state, delimiter=",", header=header, comments="")

In [4]:
df_m = pd.read_csv('COLVAR_m.csv')
df_m.head(5)

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d97,d98,d99,d100,d101,d102,d103,d104,d105,State
0,0.0,0.3163,0.9291,1.2939,1.3629,1.3847,0.4494,0.7336,0.5356,0.8012,...,0.8671,0.5315,0.5033,0.4597,0.4865,0.5697,0.8346,0.8266,0.4923,1.0
1,0.1,0.3116,0.9279,1.2780,1.3660,1.3697,0.4612,0.7712,0.5362,0.8045,...,0.8639,0.5169,0.5259,0.4539,0.4689,0.5819,0.8313,0.8347,0.4757,1.0
2,0.2,0.3049,0.9226,1.2753,1.3554,1.3673,0.4623,0.7520,0.5408,0.8025,...,0.8840,0.5207,0.5375,0.4702,0.4586,0.5274,0.8284,0.7796,0.4747,1.0
3,0.3,0.3001,0.9231,1.2647,1.4089,1.3637,0.4291,0.7776,0.5059,0.7670,...,0.8938,0.5398,0.5146,0.4662,0.4697,0.4769,0.8323,0.7353,0.4699,1.0
4,0.4,0.2919,0.9191,1.2697,1.4145,1.3574,0.4548,0.7715,0.5309,0.7903,...,0.8707,0.5259,0.5509,0.4565,0.4595,0.4981,0.8223,0.7065,0.4630,1.0

In [5]:
u = np.loadtxt('COLVAR_u')

state_column = np.full((u.shape[0], 1), 2)  
u_with_state = np.column_stack((u, state_column))

header = "time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45,d46,d47,d48,d49,d50,d51,d52,d53,d54,d55,d56,d57,d58,d59,d60,d61,d62,d63,d64,d65,d66,d67,d68,d69,d70,d71,d72,d73,d74,d75,d76,d77,d78,d79,d80,d81,d82,d83,d84,d85,d86,d87,d88,d89,d90,d91,d92,d93,d94,d95,d96,d97,d98,d99,d100,d101,d102,d103,d104,d105,State"
np.savetxt("COLVAR_u.csv", u_with_state, delimiter=",", header=header, comments="")

In [6]:
df_u = pd.read_csv('COLVAR_u.csv')
df_u.head(5)

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d97,d98,d99,d100,d101,d102,d103,d104,d105,State
0,0.0,0.5792,0.6716,1.0476,1.1995,0.2575,0.4962,0.8465,0.4495,0.6669,...,0.8663,0.5260,0.4370,0.4285,0.4802,0.3897,0.7906,0.7239,0.3995,2.0
1,0.1,0.5856,0.6733,1.0563,1.1869,0.2738,0.4995,0.8439,0.4649,0.6867,...,0.8549,0.5176,0.4422,0.4185,0.4638,0.4091,0.7885,0.7152,0.4192,2.0
2,0.2,0.5870,0.6737,1.0681,1.1972,0.2589,0.4977,0.8359,0.4486,0.6692,...,0.8465,0.5208,0.4153,0.4132,0.4832,0.3813,0.7614,0.7010,0.4232,2.0
3,0.3,0.5837,0.6755,1.0744,1.1986,0.2408,0.5029,0.8519,0.4658,0.6916,...,0.8509,0.5321,0.4693,0.4036,0.4939,0.3933,0.7534,0.6860,0.4077,2.0
4,0.4,0.5766,0.6738,1.0911,1.2014,0.2742,0.4900,0.8266,0.4630,0.6870,...,0.8598,0.5270,0.5286,0.4102,0.4753,0.4181,0.7443,0.6877,0.4364,2.0

In [8]:
df_all = pd.read_csv('COLVAR_all_state.csv')
df_all

/tmp/ipykernel_48406/2617157779.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111) have mixed types. Specify dtype option on import or set low_memory=False.
  df_all = pd.read_csv('COLVAR_all_state.csv')

,time,rmsd,rg,ic1,ic2,etoe,d1,d2,d3,d4,...,d97,d98,d99,d100,d101,d102,d103,d104,d105,State
0,0.0,0.047,0.776,0.41,0.3948,2.019,0.476,0.6962,0.5352,0.7041,...,0.9223,0.5174,0.7716,0.4435,0.4891,0.7113,0.686,0.7786,0.2968,0.0
1,0.1,0.042,0.7769,0.4319,0.3956,2.0451,0.4784,0.7403,0.5174,0.699,...,0.9494,0.5347,0.7864,0.464,0.4917,0.7133,0.6966,0.7802,0.3074,0.0
2,0.2,0.0402,0.7813,0.4468,0.3973,2.0262,0.4617,0.7167,0.5184,0.7306,...,0.9459,0.5411,0.7793,0.4533,0.4987,0.6999,0.7204,0.8016,0.3001,0.0
3,0.3,0.04,0.7808,0.4277,0.3847,2.0144,0.4652,0.7172,0.5118,0.7174,...,0.9467,0.5325,0.7788,0.4487,0.4796,0.6801,0.7284,0.7969,0.3301,0.0
4,0.4,0.0518,0.7762,0.4176,0.3959,2.005,0.4655,0.7313,0.5074,0.707,...,0.9557,0.5348,0.772,0.4618,0.5278,0.7364,0.7693,0.8481,0.3457,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30000,999.600047,0.4643,0.7371,1.1154,0.9866,1.4998,0.4693,0.8184,0.4465,0.6782,...,0.827,0.5163,0.3769,0.4169,0.4449,0.4429,0.7506,0.765,0.4113,2.0
30001,999.700047,0.462,0.739,1.105,0.9475,1.5026,0.4841,0.8569,0.4681,0.6965,...,0.8373,0.5361,0.3795,0.4156,0.48,0.4327,0.7845,0.7659,0.4198,2.0
30002,999.800047,0.4607,0.7394,1.0976,0.9314,1.4839,0.4711,0.8165,0.4602,0.6825,...,0.8299,0.5292,0.3602,0.4097,0.4856,0.4392,0.7996,0.7485,0.4264,2.0
30003,999.900047,0.4604,0.7393,1.0949,0.9301,1.4739,0.481,0.8699,0.4521,0.6781,...,0.8247,0.5246,0.3995,0.4093,0.4952,0.4201,0.7949,0.7375,0.413,2.0
30004,1000.000047,0.4657,0.7401,1.0842,0.9305,1.4701,0.4888,0.8607,0.4713,0.7048,...,0.8237,0.5417,0.3953,0.4026,0.5182,0.4206,0.7917,0.732,0.4205,2.0

In [11]:
import numpy as np

f = np.loadtxt('COLVAR_tor_f')
state_column = np.zeros((f.shape[0], 1))

f_with_state = np.column_stack((f, state_column))

header = "time,phi2,psi2,phi3,psi3,phi4,psi4,phi5,psi5,phi6,psi6,phi7,psi7,phi8,psi8,phi9,psi9,phi10,psi10,phi11,psi11,phi12,psi12,phi13,psi13,phi14,psi14,cos_ph2,cos_ps2,cos_ph3,cos_ps3,cos_ph4,cos_ps4,cos_ph5,cos_ps5,cos_ph6,cos_ps6,cos_ph7,cos_ps7,cos_ph8,cos_ps8,cos_ph9,cos_ps9,cos_ph10,cos_ps10,cos_ph11,cos_ps11,cos_ph12,cos_ps12,cos_ph13,cos_ps13,cos_ph14,cos_ps14,State"
np.savetxt("COLVAR__tor_f.csv", f_with_state, delimiter=",", header=header, comments="")

In [13]:
m = np.loadtxt('COLVAR_tor_m')
state_column = np.ones((m.shape[0], 1))

m_with_state = np.column_stack((m, state_column))

header = "time,phi2,psi2,phi3,psi3,phi4,psi4,phi5,psi5,phi6,psi6,phi7,psi7,phi8,psi8,phi9,psi9,phi10,psi10,phi11,psi11,phi12,psi12,phi13,psi13,phi14,psi14,cos_ph2,cos_ps2,cos_ph3,cos_ps3,cos_ph4,cos_ps4,cos_ph5,cos_ps5,cos_ph6,cos_ps6,cos_ph7,cos_ps7,cos_ph8,cos_ps8,cos_ph9,cos_ps9,cos_ph10,cos_ps10,cos_ph11,cos_ps11,cos_ph12,cos_ps12,cos_ph13,cos_ps13,cos_ph14,cos_ps14,State"
np.savetxt("COLVAR__tor_m.csv", m_with_state, delimiter=",", header=header, comments="")

In [14]:
u = np.loadtxt('COLVAR_tor_u')

state_column = np.full((u.shape[0], 1), 2)  
u_with_state = np.column_stack((u, state_column))

header = "time,phi2,psi2,phi3,psi3,phi4,psi4,phi5,psi5,phi6,psi6,phi7,psi7,phi8,psi8,phi9,psi9,phi10,psi10,phi11,psi11,phi12,psi12,phi13,psi13,phi14,psi14,cos_ph2,cos_ps2,cos_ph3,cos_ps3,cos_ph4,cos_ps4,cos_ph5,cos_ps5,cos_ph6,cos_ps6,cos_ph7,cos_ps7,cos_ph8,cos_ps8,cos_ph9,cos_ps9,cos_ph10,cos_ps10,cos_ph11,cos_ps11,cos_ph12,cos_ps12,cos_ph13,cos_ps13,cos_ph14,cos_ps14,State"
np.savetxt("COLVAR__tor_u.csv", u_with_state, delimiter=",", header=header, comments="")